# ─────────────────────────────────────────────────────────────
# 0. Пользователь и группа на хосте для Docker-контейнера
# ─────────────────────────────────────────────────────────────

- name: "hadmin | Ensure group exists"
  ansible.builtin.group:
    name: "{{ app_group }}"        # обычно 'hadmin'
    system: true
    state: present
  when: haproxy_admin_use_docker | bool

- name: "haproxyadmin | Ensure user exists"
  ansible.builtin.user:
    name: "{{ app_user }}"         # обычно 'haproxyadmin'
    system: true
    create_home: false
    shell: /usr/sbin/nologin
    group: "{{ app_group }}"
  when: haproxy_admin_use_docker | bool

# ---- GID группы hadmin (по имени app_group) ----
- name: "hadmin | Get group GID via getent"
  ansible.builtin.command:
    argv:
      - getent
      - group
      - "{{ app_group }}"
  register: hadmin_group_cmd
  check_mode: false
  changed_when: false
  failed_when:
    - hadmin_group_cmd.rc != 0
      or (hadmin_group_cmd.stdout.split(':') | length) < 3
  when: haproxy_admin_use_docker | bool

- name: "hadmin | Set hadmin_gid fact"
  ansible.builtin.set_fact:
    # пример строки: "hadmin:x:987:\n"
    hadmin_gid: "{{ hadmin_group_cmd.stdout.split(':')[2] | trim }}"
  when: haproxy_admin_use_docker | bool

# ---- UID/GID пользователя haproxyadmin ----
- name: "haproxyadmin | Get UID via id -u"
  ansible.builtin.command:
    argv:
      - id
      - -u
      - "{{ app_user }}"
  register: haproxyadmin_uid_cmd
  check_mode: false
  changed_when: false
  failed_when: haproxyadmin_uid_cmd.rc != 0
  when: haproxy_admin_use_docker | bool

- name: "haproxyadmin | Get GID via id -g"
  ansible.builtin.command:
    argv:
      - id
      - -g
      - "{{ app_user }}"
  register: haproxyadmin_gid_cmd
  check_mode: false
  changed_when: false
  failed_when: haproxyadmin_gid_cmd.rc != 0
  when: haproxy_admin_use_docker | bool

- name: "haproxyadmin | Set haproxy_admin_uid/gid facts"
  ansible.builtin.set_fact:
    haproxy_admin_uid: "{{ haproxyadmin_uid_cmd.stdout | trim }}"
    haproxy_admin_gid: "{{ haproxyadmin_gid_cmd.stdout | trim }}"
  when: haproxy_admin_use_docker | bool
